version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: autoprefixer
    versions:
    - 10.2.3
    - 10.2.4
  - dependency-name: react-test-renderer
    versions:
    - 17.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: redux
    versions:
    - 4.0.5
